function createfigure(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 13-Mar-2017 14:17:38

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(Y1);

% Create xlabel
xlabel('time/ms');

% Create ylabel
ylabel('EMG Signal/mV');

